#eureka.instance.prefer-ip-address=true
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761

management:
  endpoints:
    web:
      exposure:
        include: *
  security:
    enabled: false
