spring:
  cloud:
    stream:
      bindings:
        input:
          destination: rooms
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8080/eureka
